### PR TITLE
feat: added button to stop searching for a buddy

### LINKED ISSUE #132: [FEATURE] add stop button
### Description

We have a button to start searching for someone to talk to, but we don't have one for when someone wants to stop searching.

**Tasks**
- [ ] add stop button, should have the same styles as the stop button, but smaller
- [ ] when clicked should stop searching for a a user

### PR DESCRIPTION
**Pull request by ays14**
# Fixes Issue

closes #132 

# 👨‍💻 Changes proposed(What did you do ?)

Created a button titled as `Stop` in `BuddyMatcher.jsx` which is a link to `/` and redirects you to home on click. Since, there is an effect with the callback that closes the socket and does necessary steps when component unmounts. Therefore, I need not worry about the same when redirecting to `/` with react-router.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots
image

### CODE REVIEW

**Comment by ays14** [comment]
@Dun-sin there you go, for your convention a different branch. I hope you will update your rules to ask contributors to follow the convention for your repository.

**Comment by Dun-sin** [comment]
> @Dun-sin there you go, for your convention a different branch. I hope you will update your rules to ask contributors to follow the convention for your repository.

I did, don't know if you mean a rephrase because here it is 👇🏾
image

**Comment by Dun-sin** [comment]
This PR doesn't fix the issue, the user is still on the waiting line for connecting with someone else, it has to totally stop

**Comment by ays14** [comment]
> This PR doesn't fix the issue, the user is still on the waiting line for connecting with someone else, it has to totally stop, don't know if it's a miscommunication, but this PR should fix the following:
> 
> * remove the user was the waiting queue array in the backend
> * send successful using socketio as used in this project to the frontend
> * then changes the route back to the root

Oh okay, let me figure this out to an approach and ping you before going ahead on code.

**Comment by Dun-sin** [comment]
@ays14 what you just did with the contributing file is none of this PRs business, so kindly delete and create a separate issue

**Comment by ays14** [comment]
Approach:
* send an API call to execute a function at backend `a`
* `a` will then update the waiting list of users and emit a socket conn to message UI about successful removal
* @Dun-sin what is the scale of your application? Depending on the scale, the removal has to be a in-place or new array.
* UI will then redirect to the root after receiving a success.

**Comment by ays14** [comment]
> @ays14 what you just did with the contributing file is none of this PRs business, so kindly delete and create a separate issue

This was already removed within seconds after the push.

**Comment by Dun-sin** [comment]
> Approach:
> 
>     * send an API call to execute a function at backend `a`
> 
>     * `a` will then update the waiting list of users and emit a socket conn to message UI about successful removal
> 
>     * @Dun-sin what is the scale of your application? Depending on the scale, the removal has to be a in-place or new array.
> 
>     * UI will then redirect to the root after receiving a success.



> Approach:
> 
>     * send an API call to execute a function at backend `a`
> 
>     * `a` will then update the waiting list of users and emit a socket conn to message UI about successful removal
> 
>     * @Dun-sin what is the scale of your application? Depending on the scale, the removal has to be a in-place or new array.
> 
>     * UI will then redirect to the root after receiving a success.

It has a backend, frontend, and a database
this line is where all the users searching are being stored
https://github.com/Dun-sin/Whisper/blob/421ebac47b8a076cc9b7c810fc02b094a2d1b577/server/lib.js#L42

there's already a function to handle removing a user from the searching object
https://github.com/Dun-sin/Whisper/blob/421ebac47b8a076cc9b7c810fc02b094a2d1b577/server/lib.js#L448

you just need to create a socket event to detect when a user clicks the stop button

**Comment by ays14** [comment]
@Dun-sin does this look good?

server: index.js
```js
socket.on('stop_search', async ({ loginId, email }) => {
        await delWaitingUser(loginId ?? email);
        socket.emit('stop_search_success');
    });
```

client: BuddyMatcher.jsx
```jsx
    const handleStopSearch = () => {
        socket.emit('stop_search', { loginId: auth.loginId, email: auth.email });
        setIsStoppingSearch(true);
    };

    useEffect(() => {
        setLoadingText(isStoppingSearch ? stoppingSearchLoadingText : defaultLoadingText);
    }, [isStoppingSearch]);
...
   useEffect(() => {
...
        socket.on('stop_search_success', () => {
            navigate('/');
        });
...
, [])

return isFound ? ... :
{!isStoppingSearch && <button
                onClick={handleStopSearch}
                className={
                    'hover:no-underline hover:text-white font-medium text-white text-[1.5em] w-[8em] h-[2.3em] mt-4 rounded-[30px] border-4 border-solid border-[#f04336] flex flex-col items-center justify-center'
                }
            >
                Stop
            </button>}
```

**Comment by Dun-sin** [comment]
looks good

**Comment by Dun-sin** [comment]
Also, change the colour for the stop button, let it not be a border but a background of #FF3A46 hex color

**Comment by mathiasayivor** [comment]
> @Dun-sin does this look good?
> 
> server: index.js
> 
> ```js
> socket.on('stop_search', async ({ loginId, email }) => {
>         await delWaitingUser(loginId ?? email);
>         socket.emit('stop_search_success');
>     });
> ```
> 
> client: BuddyMatcher.jsx
> 
> ```js
>     const handleStopSearch = () => {
>         socket.emit('stop_search', { loginId: auth.loginId, email: auth.email });
>         setIsStoppingSearch(true);
>     };
> 
>     useEffect(() => {
>         setLoadingText(isStoppingSearch ? stoppingSearchLoadingText : defaultLoadingText);
>     }, [isStoppingSearch]);
> ...
>    useEffect(() => {
> ...
>         socket.on('stop_search_success', () => {
>             navigate('/');
>         });
> ...
> , [])
> 
> return isFound ? ... :
> {!isStoppingSearch && <button
>                 onClick={handleStopSearch}
>                 className={
>                     'hover:no-underline hover:text-white font-medium text-white text-[1.5em] w-[8em] h-[2.3em] mt-4 rounded-[30px] border-4 border-solid border-[#f04336] flex flex-col items-center justify-center'
>                 }
>             >
>                 Stop
>             </button>}
> ```

@ays14 change the following:
```
socket.on('stop_search', async ({ loginId, email }) => {
        await delWaitingUser(loginId ?? email);
        socket.emit('stop_search_success');
    });
```

to:
```
socket.on('stop_search', async ({ loginId, email }) => {
        await delWaitingUser(email ?? loginId);
        socket.emit('stop_search_success');
    });
```

**Comment by Dun-sin** [comment]
@ays14 did you test this? because it shows stopping search but never does

**Comment by Dun-sin** [comment]
@ays14 sorry never mind, it's not your fault lol

**Pull request merged**
