### PR TITLE
refactor: observer in MessageSeen.jsx

### LINKED ISSUE #669: [OTHER] move the observer into a hook from the messageseen component
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat/MessageSeen.jsx#L29-L68

### PR DESCRIPTION
**Pull request by damirgros**
# Fixes Issue

**My PR closes #669**

# 👨‍💻 Changes proposed(What did you do ?)

Refactored observer logic in the "MessageSeen.jsx" by creating useObserver hook in the new file "useObserver.js" in the folder "hooks".

Transfered observer logic from "MessageSeen.jsx" to "useObserver.js" and also memoized it so it doesn't get re-created every time component re-renders.

Removed unused imports from "MessageSeen.jsx" and initiated observer variable with useObserver hook.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
@damirgros great work just one thing, can you replace the code with a text description of what you did this is because we can see the code in the code tab already, but we won't see a text description.

**Comment by Dun-sin** [comment]
in production, this doesn't work:
brave_XFr2dt6FKQ

**Comment by damirgros** [comment]
Intersection Observer API doesn't have connect method.

Can you try in production only changing useEffect in MessageSeen.jsx to look like this (I added the check for if observer and sortedMessages exist, removed observer.connect and added observer dependancy):

```js
useEffect(() => {
		// Only proceed if the observer and sortedMessages are available
		if (!observer || !sortedMessages.length) return;

		sortedMessages.forEach((message) => {
			if (message.isRead) return;

			const messageElement = document.getElementById(`message-${message.id}`);
			if (messageElement && isTabVisible) {
				observer.observe(messageElement); 
			}
		});

		return () => {
			if (observer) observer.disconnect();
		};
	}, [sortedMessages, isTabVisible, observer]);
```

**Comment by Dun-sin** [comment]
> Intersection Observer API doesn't have connect method.
> 
> Can you try in production only changing useEffect in MessageSeen.jsx to look like this (I added the check for if observer and sortedMessages exist, removed observer.connect and added observer dependancy):
> 
> ```js
> useEffect(() => {
> 		// Only proceed if the observer and sortedMessages are available
> 		if (!observer || !sortedMessages.length) return;
> 
> 		sortedMessages.forEach((message) => {
> 			if (message.isRead) return;
> 
> 			const messageElement = document.getElementById(`message-${message.id}`);
> 			if (messageElement && isTabVisible) {
> 				observer.observe(messageElement); 
> 			}
> 		});
> 
> 		return () => {
> 			if (observer) observer.disconnect();
> 		};
> 	}, [sortedMessages, isTabVisible, observer]);
> ```

Push it to GitHub and I'll set it up here

**Comment by damirgros** [comment]
It is pushed.

**Comment by Dun-sin** [comment]
> @damirgros great work just one thing, can you replace the code with a text description of what you did this is because we can see the code in the code tab already, but we won't see a text description.
> 
> And a good convention is to delete a fork to follow a linear history on GitHub, this is so your code doesn't combine the last code which was already merged. Or you could just create a new branch from the main and then pull it so it's linear (**for this one, no need to delete the PR just a correction**)

Alright it works in prod, also address this please the first one

**Review by Dun-sin — APPROVED** [review]
looks great, thanks for it.

**Comment by damirgros** [comment]
> > @damirgros great work just one thing, can you replace the code with a text description of what you did this is because we can see the code in the code tab already, but we won't see a text description.
> > And a good convention is to delete a fork to follow a linear history on GitHub, this is so your code doesn't combine the last code which was already merged. Or you could just create a new branch from the main and then pull it so it's linear (**for this one, no need to delete the PR just a correction**)
> 
> @damirgros Alright it works in prod, also address this please the first one

Added text description in the PR

**Pull request merged**
