### PR TITLE
Fixes: message not clearing after form submission in Chat component

### LINKED ISSUE #417: [BUG] Message Input not cleared after message is sent
### Description

Message Input is not cleared after message is submitted/sent

### Screenshots

[Screencast from 15-10-23 11:26:40.webm](https://github.com/Dun-sin/Whisper/assets/74247733/d58e5543-052f-479c-86fb-7ee97fbcc51b)

### Additional information

_No response_

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by dev-palwar**
# Fixes Issue

**My PR closes  #417**

# 👨‍💻 Changes proposed(What did you do ?)
Changed the state of message to empty string after message is sent.
Also, I would like to add that only this part of the code is changed by me in chat.JSX component 

> if (inputRef.current) {
			inputRef.current.value = ''; // Clear the input field
			setMessage(''); // Reset the state of the message to an empty string
			inputRef.current.focus();
		}

other changes seen in files changed are done by the prettier extension that i have in my VsCode 

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR are clear and explain the approach.

### CODE REVIEW

**Comment by Dun-sin** [comment]
> # PR Compliance Checks
> 
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> ## Issue Reference In order to be considered for merging, the pull request description must refer to a specific issue number. This is described in our [Contributing Guide](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md). This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue number that this PR is meant to address.
> ## Conventional Commit PR Title
> 
> In order to be considered for merging, the pull request title must match the specification in [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass. Most often, our PR titles are something like one of these:
> 
>     * docs: correct typo in README
> 
>     * feat: implement dark mode"
> 
>     * fix: correct remove button behavior
> 
> 
> Linting Errors
> 
>     * Found type "Fixes", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"

@dev-palwar 
Please fix this error, if you don't know how, try this:
- Read the error carefully or read the contributing file
- Checkout past merged Pull requests to see how they were done for it to be merged

> Note: you can edit your PR message, this PR won't be merged if the error isn't gone and you have a week max to fix it before the PR gets closed without being merged

**Review by Dun-sin — CHANGES_REQUESTED** [review]
this is hard to review, remove all format changes

**Comment by Dun-sin** [comment]
@dev-palwar do you not want to work on this anymore?

**Comment by dev-palwar** [comment]
Ok. I have made another PR check it #443

**Pull request closed without merging**
