### PR TITLE
feat: Implement logout button

### LINKED ISSUE #47: [FEATURE] Add Logout button
### Description

Currently after logging, there's no way to logout from the app beside manually changing `localStorage.isLogged = false`.
This is would be a follow up on #36 and #14 
With this, I think the we'd have a complete auth system for the app

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by dhfherna**
## 🛠️ Fixes Issue

Closes #47

## 👨‍💻 Changes proposed

* Created a Logout file reusing AuthContext logic
* Created a logout function 
* Implement a button in the Navbar

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

image

### CODE REVIEW

**Comment by Dun-sin** [comment]
> This pr does not solve logout completely, since it only clears the client's data. 
> As a result, other connections would still be left open e.g opened chats, etc.
> But since the original issue only proposed adding a Logout "button", it is technically complete.

I think it's fair that chats should be open, because someone can be logged in on their phone and just log out of their laptop, it will keep the chats open in mobile

**Comment by mathiasayivor** [comment]
> > This pr does not solve logout completely, since it only clears the client's data.
> > As a result, other connections would still be left open e.g opened chats, etc.
> > But since the original issue only proposed adding a Logout "button", it is technically complete.
> 
> I think it's fair that chats should be open, because someone can be logged in on their phone and just log out of their laptop, it will keep the chats open in mobile

I get you, but what if there's only one connected device?
I think the current backend implementation provides enough information to handle edge cases like you described

**Comment by Dun-sin** [comment]
> I get you, but what if there's only one connected device?
> I think the current backend implementation provides enough information to handle edge cases like you described

I still think it's okay, because a user can logout on all devices to login on a new one also.

**Comment by dhfherna** [comment]
I have updated this PR reusing backend logic to logout. I hope it is a better way.

**Comment by mathiasayivor** [comment]
> I have updated this PR reusing AuthContext logic to logout. I hope it is a better way.

I think it's still frontend, but LGTM

**Comment by Dun-sin** [comment]
> > I have updated this PR reusing AuthContext logic to logout. I hope it is a better way.
> 
> I think it's still frontend, but LGTM

We can create another issue for further features related to this

**Review by Dun-sin — APPROVED** [review]
Thanks For Contributing, PR accepted, I hope you continue to contribute to this project

Check out the community discord server [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by dhfherna** [comment]
> Thanks For Contributing, PR accepted, I hope you continue to contribute to this project
> 
> Check out the community discord server [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

It was a pleasure, is it possible to add the hacktoberfest-accepted tag?

**Pull request merged**
