### PR TITLE
docs: correct link in README

### LINKED ISSUE #92: [DOCS] wrong link in README
### Description

`View Demo` has a wrong link, replace it with the proper link to the site, which can be found in about section of this repo

### Screenshots

image

### PR DESCRIPTION
**Pull request by cesar-codes**
## 🛠️ Fixes Issue

Fix 'View Demo' link in README.md linking to wrong location.

`Closes #92`

## 👨‍💻 Changes proposed

Previously: https://github.com/Dun-sin/Whisper/issues/new?assignees=&labels=bug&template=bug_report.md&title=
Now: https://whischat.vercel.app/

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by cesar-codes — COMMENTED** [review]
Hi, can you please review and let me know if I need to make changes to the commit? Thanks.

**Comment by Dun-sin** [comment]
> Hi, can you please review and let me know if I need to make changes to the commit? Thanks. 

Hi, the github action is talking about the commit and the PR title

**Review by Dun-sin — APPROVED** [review]
Thanks For Contributing, PR accepted, I hope you continue to contribute to this project

Check out the community discord server [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by cesar-codes** [comment]
Thanks @Dun-sin ! I've gone ahead and joined the Discord. 
For this PR, do I need to try a new commit with a better title to get it pulled and merged?

**Comment by Dun-sin** [comment]
> Thanks @Dun-sin ! I've gone ahead and joined the Discord. 
> For this PR, do I need to try a new commit with a better title to get it pulled and merged?

Thanks for joining, no it's not asking for a change to your commit but a change to your PR title also

**Comment by cesar-codes** [comment]
Hi, I have changed the title, but it looks like it's still failing?

**Comment by Dun-sin** [comment]
> PR Compliance Checks Passed!

It passed

**Pull request merged**
