### PR TITLE
docs: removed kinde from readme

### LINKED ISSUE #648: [DOCS] remove kinde from readme
### Description

Remove this set of lines:
https://github.com/Dun-sin/Whisper/blob/6be5111a1502ea0fc7bdf7b3f89ab0c84f3929ae/README.md?plain=1#L63-L66

and change this text from
https://github.com/Dun-sin/Whisper/blob/6be5111a1502ea0fc7bdf7b3f89ab0c84f3929ae/README.md?plain=1#L141
to ```To test things out, you can open the same URL in two different browsers or open a private browsing window in the same browser. This allows you to connect to yourself, use `login anonymously` if you aren't dealing with anything that uses user data, else use `login` and open an account on [mailtrap](https://mailtrap.io/) using their demo to domain and get the token into .env```

### Screenshots

_No response_

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by hanzla-sib**
My PR fixes #648 

👨‍💻 Changes proposed(What did you do ?)
# ✔️ Check List (Check all the applicable boxes)

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
> # PR Compliance Checks
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project.  The results are listed in the  following section.
> 
> ## Conventional Commit PR Title
> In order to be considered for merging, the pull request title must match the specification in  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass.
> Most often, our PR titles are something like one of these:
> - docs: correct typo in README
> - feat: implement dark mode"
> - fix: correct remove button behavior
> 
> Linting Errors
> 
> - Found type "null", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"
> - No subject found

Please fix this error, if you don't know how, try this:
- Read the error carefully or read the contributing file
- Checkout past merged Pull requests to see how they were done for it to be merged e.g #651

> Note: you can edit your PR message, this PR won't be merged if the error isn't gone and you have a week max to fix it before the PR gets closed without being merged

**Comment by hanzla-sib** [comment]
> > # PR Compliance Checks
> > Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project.  The results are listed in the  following section.
> > ## Conventional Commit PR Title
> > In order to be considered for merging, the pull request title must match the specification in  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass.
> > Most often, our PR titles are something like one of these:
> > 
> > * docs: correct typo in README
> > * feat: implement dark mode"
> > * fix: correct remove button behavior
> > 
> > Linting Errors
> > 
> > * Found type "null", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"
> > * No subject found
> 
> @hanzla-sib fix this error, if you don't know how, try this:
> 
> * Read the error carefully or read the contributing file
> * Checkout past merged Pull requests to see how they were done for it to be merged e.g [docs: fixed anchor ref in contributing.md #651](https://github.com/Dun-sin/Whisper/pull/651)
> 
> > Note: you can edit your PR message, this PR won't be merged if the error isn't gone and you have a week max to fix it before the PR gets closed without being merged

image

now i think its ok the other 2 should be done by you or is there any mistake?

**Comment by Dun-sin** [comment]
> now i think its ok the other 2 should be done by you or is there any mistake?

Nope you're good

**Comment by Dun-sin** [comment]
@hanzla-sib actually two mistakes, one being you should link the issue you're fixing and not the pull request, second is your issue addresses two things and you only did one

**Comment by hanzla-sib** [comment]
> @hanzla-sib actually two mistakes, one being you should link the issue you're fixing and not the pull request, second is your issue addresses two things and you only did one

Screenshot_20240813-020642


> @hanzla-sib actually two mistakes, one being you should link the issue you're fixing and not the pull request, second is your issue addresses two things and you only did one


ok my bad i thought that i have to remove the set of line and put the below line of the place where i removed the lines.
tommorrow morning i will correct it and then again commit the changes thanks.

**Comment by hanzla-sib** [comment]
> > @hanzla-sib actually two mistakes, one being you should link the issue you're fixing and not the pull request, second is your issue addresses two things and you only did one
> 
> Screenshot_20240813-020642
> 
> > @hanzla-sib actually two mistakes, one being you should link the issue you're fixing and not the pull request, second is your issue addresses two things and you only did one
> 
> ok my bad i thought that i have to remove the set of line and put the below line of the place where i removed the lines. tommorrow morning i will correct it and then again commit the changes thanks.

and i also linked the pr with issue

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by hanzla-sib** [comment]
> You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.
> 
> Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

yeah thanks

**Pull request merged**
