### PR TITLE
feat: add theming option

### PR DESCRIPTION
**Pull request by nkirukka**
# Fixes [#193 ](https://github.com/Dun-sin/Whisper/issues/193)

**My PR closes [#193](https://github.com/Dun-sin/Whisper/issues/193)**

# 👨‍💻 Changes proposed
- Added feature for changing theme from dark to light and vice versa
- Change persists on refresh

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

##  Note to reviewers
I would like some tips on how I can trigger 'Update Settings' when the theme button is 
clicked, I tried but couldn't figure it out, so right now it updates in place.

# 📷 Video demo
https://user-images.githubusercontent.com/72361299/207576135-3e29aff7-9869-4df2-bbd9-86de239479b3.mp4

### CODE REVIEW

**Comment by Dun-sin** [comment]
It's fine the way it is, but since it doesn't need to be updated manually like the rest, it should be below all the other settings and the update button

**Comment by nkirukka** [comment]
Alright. Will fix and pull again

**Comment by nkirukka** [comment]
Updated with changes on review.

### Video showing updated look
https://user-images.githubusercontent.com/72361299/208094478-d8b4855a-49a6-4658-b0c5-3cbdcfc1ee99.mp4

@Dun-sin

**Comment by Dun-sin** [comment]
> Updated with changes on review.
> 
> ### Video showing updated look
> https://user-images.githubusercontent.com/72361299/208094478-d8b4855a-49a6-4658-b0c5-3cbdcfc1ee99.mp4
> 
> @Dun-sin 

Looks great, thank you

**Comment by nkirukka** [comment]
> You need to do a git pull, to fix the build error

git pull? Could you clarify? My repo is synced with origin already.

**Comment by Dun-sin** [comment]
> > You need to do a git pull, to fix the build error
> 
> git pull? Could you clarify? My repo is synced with origin already.

Really?
I'm probably missing

**Comment by Dun-sin** [comment]
Alright it works almost fine, you just missing something.
The chat section doesn't have the change, every other page does.

**Comment by Dun-sin** [comment]
hi @nkirukka, are you still interested in finishing this up?

**Comment by nkirukka** [comment]
> hi @nkirukka, are you still interested in finishing this up?
 
 
Yes please. Will finish this weekend.

**Comment by Dun-sin** [comment]
> > hi @nkirukka, are you still interested in finishing this up?
>  
>  
> Yes please. Will finish this weekend. 
> 

Okay, thank you

**Comment by nkirukka** [comment]
> Alright it works almost fine, you just missing something. The chat section doesn't have the change, every other page does.
> 
> Screenshot_2022-12-16-21-12-13-444_org mozilla firefox

@Dun-sin I’m not able to create a chat. Page is stuck on “Looking for a random buddy…”. Is there a work around? I need to be able to see the page to see that the changes I make are taking effect.

**Comment by Dun-sin** [comment]
> > Alright it works almost fine, you just missing something. The chat section doesn't have the change, every other page does.
> > 
> > Screenshot_2022-12-16-21-12-13-444_org mozilla firefox
> 
> @Dun-sin I’m not able to create a chat. Page is stuck on “Looking for a random buddy…”. Is there a work around? I need to be able to see the page to see that the changes I make are taking effect. 

You could follow the instruction steps in the readme file of the project. It relies alot on the backend, but you don't need to know it, just start the mongodb server and the backend side, skip docker.

If you need further help, let me know

**Comment by nkirukka** [comment]
Alright, thank you

**Comment by nkirukka** [comment]
I followed the instructions on the readme to the T but I'm getting this error:
nodemon-err

### Here's my env.sample
env-sample

**Comment by Dun-sin** [comment]
> I followed the instructions on the readme to the T but I'm getting this error: nodemon-err
> ### Here's my env.sample
> 
> env-sample

because the name should be .env, .env-sample is an example of what to place in .env file, as it says here
image

**Comment by nkirukka** [comment]
Backend is up and running but I still can't find a buddy to chat with.

### Server
be

### Client
stuck

What else could I be doing wrong?

**Comment by Dun-sin** [comment]
> Backend is up and running but I still can't find a buddy to chat with.
> 
> ### Server
> be
> 
> ### Client
> stuck
> 
> What else could I be doing wrong?

You have to open two different browsers(could also be your browser and a private one)

So you can connect with yourself and test things out🙌🏽

I forgot to mention that sorry🤞🏽

**Comment by Dun-sin** [comment]
Hi @nkirukka were you able to figure this out?

**Comment by Dun-sin** [comment]
Hi @nkirukka asking for an update again on this

**Pull request closed without merging**
