### PR TITLE
fix: other issue template not showing up

### LINKED ISSUE #299: [BUG]: other issue template not showing up
### Description

To fix this, remove the commas at the end of this two lines
https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/.github/ISSUE_TEMPLATE/other.yml#L3-L4

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by ronisarkarexe**
Fixes Issue

closes #299

# 👨‍💻 Changes proposed(What did you do ?)
- By removing the commas, I fixed the issue of the other template not showing up.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by ronisarkarexe** [comment]
@Dun-sin is it ok?

**Review by Dun-sin — APPROVED** [review]
Your PR is accepted thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by Dun-sin** [comment]
> @Dun-sin is it ok?

Yes, do you want me to merge it when Hacktoberfest starts?

**Comment by ronisarkarexe** [comment]
> > @Dun-sin is it ok?
> 
> Yes, do you want me to merge it when Hacktoberfest starts?

Yes, thank you.

**Pull request merged**
