### PR TITLE
fix: close dialog after logging out

### LINKED ISSUE #644: [BUG] logout dialogue still showing after user has logged out
### Description

<as the title says>

### Screenshots

image

### Additional information

_No response_

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by malakbenr**
# Fixes Issue

**My PR closes #644*

# 👨‍💻 Changes proposed(What did you do ?)
- I closed the dialog after logging out by by updating the state of setDialog in the logOut function.
# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
Please edit your PR adding what you did to fix the issue, this is to help with documentation here's an example: #543

**Comment by malakbenr** [comment]
> Please edit your PR adding what you did to fix the issue, this is to help with documentation here's an example: #543
> 
> You don't need to close the PR just edit the current one

Done.

**Review by Dun-sin — APPROVED** [review]
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Comment by malakbenr** [comment]
> You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.
> 
> Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others.

Thank you for the kind words! I'm really glad to have been able to contribute to this project and look forward to continuing to do so.

**Pull request merged**
