### PR TITLE
feat: Add custom dialog

### LINKED ISSUE #177: [FEATURE] Use modal for Logout instead of native alert
### Description

When logging out, the app use the browser's alert to confirm. We could make this better using customize dialog/modal instead for better UI. 
I could work on this.

### Screenshots

image

### PR DESCRIPTION
**Pull request by Manethpak**
# Fixes Issue

**My PR closes #177**

# 👨‍💻 Changes proposed(What did you do ?)

Create a new Dialog component that will be used throughout the project instead of using browser's native alert. Screenshot below show what the dialog looked like added to the logout and chat close function.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

image

image

### CODE REVIEW

**Comment by Dun-sin** [comment]
Doesn't look good on mobile

**Comment by Dun-sin** [comment]
Also pls pull the latest changes to this and make sure they work properly
- edit doesn't work
- typing status is buggy

Just to be safe

**Comment by Manethpak** [comment]
Thank for the feedback, I'll check on the point that you mentioned

**Comment by Manethpak** [comment]
@Dun-sin As you mentioned 
- I have fixed the dialog to be more responsive
- Refactor it to has typehint 
I'm not quite sure what do you mean by edit doesnt work but if you could elaborate it here, I'm happy to work on it. Sorry if I make a lot of mistake I'm new to open-source contribution, so if you could bare with me.

**Comment by mathiasayivor** [comment]
@Manethpak great work, but why not just use the dialog component provided by [RSuite](https://rsuitejs.com/components/modal)?
It's mobile responsive and can be customized, plus it already being used in the app...

**Comment by Manethpak** [comment]
@mathiasayivor That was my bad, I didn't know you had a UI library installed. I read through the project's code and mostly the UI are all written by hand that's why I decided to write one as well

**Comment by Dun-sin** [comment]
> @mathiasayivor That was my bad, I didn't know you had a UI library installed. I read through the project's code and mostly the UI are all written by hand that's why I decided to write one as well

@Manethpak still doesn't look good on mobile
image

**Pull request closed without merging**
