### PR TITLE
style: change the span to button for badword element #666

### LINKED ISSUE #666: [OTHER] change the span to a button for the is bad words element
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L502-L513

### Additional information

This issue depends on #663 

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by Gopal-001**
**My PR closes #666 **

# 👨‍💻 Changes proposed(What did you do ?)
image
Did few changes:

1. Replaced span with button.
2. Added some styling to button and on hover button.
3. Added a gap between the text and button.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

Normal : <br>
image
<br>
On hover: <br>
image

### CODE REVIEW

**Comment by Gopal-001** [comment]
@Dun-sin pls review the code, glad to have some feedback.
I was facing issue to go to the component as i visited the actually site (not able to connect to some user...  something like that) and also tried to bypass the searching for user in local env. But when nothing works so tried to directly call the badwords component via app to see the changes, so if there is some styling change required pls tell.

**Review by Dun-sin — CHANGES_REQUESTED** [review]
@Gopal-001 please stick to the issue description and just change it from button to span, if you have any UI suggestion change, please create a seperate issue

**Comment by Gopal-001** [comment]
@Dun-sin reverted the style changes however removed the cursor-pointer as button automatically handles it.

**Review by Dun-sin — APPROVED** [review]
You did great @Gopal-001, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Pull request merged**
