### PR TITLE
feat: added functionality for the profile page

### LINKED ISSUE #214: [FEATURE] add functionality for the profile page
### Description

This issue depends on #239 

Tasks:
- [ ] this page should not be accessible to non email users (users that didn't log in with their email)
- [ ] use the existing model for user profile
- [ ] save the details of the user to the database

### Screenshots

_No response_

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

_No response_

### PR DESCRIPTION
**Pull request by ishan-siddiqui**
# Fixes Issue

**My PR closes #214**

# 👨‍💻 Changes proposed(What did you do ?)

- Made the page non-accessible at the backend to prevent non-email users from accessing the profile page.
- Updated existing UserSchema model, added 3 new fields - gender, age, and aboutMe to include more data on the profile page.
- Developed anew endpoint, /updateProfile/:id, that allows users to update their profile information.
- Added new function in server/index.js that handles the update request.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

Kindly check issue #214 for reference
# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
> # PR Compliance Checks
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project.  The results are listed in the  following section.
> 
> ## Watched Files
> This pull request modifies specific files that require careful review by the maintainers.
> 
> Files Matched
> 
> - package-lock.json

@ishan-siddiqui please fix this

**Comment by ishan-siddiqui** [comment]
@Dun-sin the package-lock.json file is not being added to staging area.

Screenshot 2023-08-08 at 2 05 52 PM

Should I remove the node_modules from the .gitignore file
Screenshot 2023-08-08 at 2 06 23 PM
 please let me know if there is any alternate method that you think I should use to resolve this problem.

**Comment by Dun-sin** [comment]
> @Dun-sin the package-lock.json file is not being added to staging area.
> 
> Screenshot 2023-08-08 at 2 05 52 PM
> 
> Should I remove the node_modules from the .gitignore file
> Screenshot 2023-08-08 at 2 06 23 PM
>  please let me know if there is any alternate method that you think I should use to resolve this problem.
> 

It's not needed, no issue with it, removing node_modules means it will be pushed to github, which isn't good💁 and issue is to not add it and remove it from this pull request, you are trying to do the exact opposite

**Comment by ishan-siddiqui** [comment]
> # PR Compliance Checks
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> 
> ## Watched Files
> This pull request modifies specific files that require careful review by the maintainers.
> 
> Files Matched
> 
> * package-lock.json

@Dun-sin I have fixed this issue by adding the original package-lock.json file from the 213 branch. Please let me know if you would like me to check anything else before we go ahead with the merge request.

**Comment by Dun-sin** [comment]
> > # PR Compliance Checks
> > Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> > 
> > ## Watched Files
> > This pull request modifies specific files that require careful review by the maintainers.
> > 
> > Files Matched
> > 
> > * package-lock.json
> 
> @Dun-sin I have fixed this issue by adding the original package-lock.json file from the 213 branch. Please let me know if you would like me to check anything else before we go ahead with the merge request.

You are frustrating me😩 it says don't have any package.lock.json file at all in your PR. That's what it means, it should just be the code file

**Comment by ishan-siddiqui** [comment]
> > > # PR Compliance Checks
> > > Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> > > ## Watched Files
> > > This pull request modifies specific files that require careful review by the maintainers.
> > > Files Matched
> > > 
> > > * package-lock.json
> > 
> > 
> > @Dun-sin I have fixed this issue by adding the original package-lock.json file from the 213 branch. Please let me know if you would like me to check anything else before we go ahead with the merge request.
> 
> You are frustrating me😩 it says don't have any package.lock.json file at all in your PR. That's what it means, it should just be the code file

My apologies. I thought it to be the other way around. I will remove the file from my repository and then make the commit with just the code file.

**Comment by Dun-sin** [comment]
> > > > # PR Compliance Checks
> > > > Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> > > > ## Watched Files
> > > > This pull request modifies specific files that require careful review by the maintainers.
> > > > Files Matched
> > > > 
> > > > * package-lock.json
> > > 
> > > 
> > > @Dun-sin I have fixed this issue by adding the original package-lock.json file from the 213 branch. Please let me know if you would like me to check anything else before we go ahead with the merge request.
> > 
> > You are frustrating me😩 it says don't have any package.lock.json file at all in your PR. That's what it means, it should just be the code file
> 
> My apologies. I thought it to be the other way around. I will remove the file from my repository and then make the commit with just the code file.

The problem with that is that it will delete it from the main repo, the best thing is to create a new PR with the proper files

**Comment by ishan-siddiqui** [comment]
Ok. Will make new PR with proper files.

**Pull request closed without merging**
