### PR TITLE
fix: solve responsiveness issue

### LINKED ISSUE #75: Responsiveness Issue
### Description

In small devices, everything in the start (or search) screen appears quite big. Even in other tabs, text appears quite big.

### Screenshots

IMG_20220911_184141

### PR DESCRIPTION
**Pull request by pushkaraj2007**
## 🛠️ Fixes Issue

Closes #75

## 👨‍💻 Changes proposed

- Changed the font size of some texts for better responsiveness.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
Whisper-responsiveness-issue

### CODE REVIEW

**Comment by pushkaraj2007** [comment]
How it looks now?

**Comment by pushkaraj2007** [comment]
Hey @Dun-sin 

Are you going to merge PR as "hacktoberfest-accepted"?

**Comment by pushkaraj2007** [comment]
@Dun-sin 

Any changes required for this PR?

**Comment by Dun-sin** [comment]
> @Dun-sin 
> 
> Any changes require for this PR? 

Would be nice to use calc or clamp, so it doesn't look small on bigger screens

**Comment by pushkaraj2007** [comment]
Great! I'll make the changes soon...

**Comment by pushkaraj2007** [comment]
@Dun-sin 

What about media-queries for this?

**Comment by Dun-sin** [comment]
> @Dun-sin 
> 
> What about media-queries for this? 

I try to avoid media queries

[Checkout this article](https://benborgers.com/posts/tailwind-calc)

**Comment by pushkaraj2007** [comment]
Ok great, thanks!

Commit is on the way...

**Comment by pushkaraj2007** [comment]
Made the changes.

Please have a look, @Dun-sin

**Review by Dun-sin — APPROVED** [review]
Thanks For Contributing, PR accepted, I hope you continue to contribute to this project

Check out the community discord server [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Pull request merged**
