### PR TITLE
refactor: move reconnect banner to a new component

### LINKED ISSUE #662: [OTHER] move the reconnect banner to its own component
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/BuddyMatcher.jsx#L261-L277

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by LuseBiswas**
# Fixes Issue

**My PR closes #662 **

# 👨‍💻 Changes proposed(I had made another component inside component 📁 named as ReconnectBanner.jsx and import it in BuddyMatcher.jsx)

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by LuseBiswas** [comment]
@Dun-sin I think Now I had complete the Compilance/PR Checks .
I had setup the code locally before, but due to the issue I had to delete it. But my codes work fine.
You can check at your own to. Hope it get merged soon.

**Comment by Dun-sin** [comment]
> @Dun-sin I think Now I had complete the Compilance/PR Checks .
> I had setup the code locally before, but due to the issue I had to delete it. But my codes work fine.
> You can check at your own to. Hope it get merged soon.

If you can't test it locally, you can use the preview link from vercel right here in the PR and attach the screen recording

**Comment by Dun-sin** [comment]
@LuseBiswas you also need to remove the package.json file from your PR, don't delete it, remove it. There's a difference please

**Comment by Dun-sin** [comment]
@LuseBiswas looks like your build fails

**Pull request closed without merging**
