### PR TITLE
feat: allow users to close a chat on the home screen

### LINKED ISSUE #677: [FEATURE] allow users to close a chat on the home screen
### Description

A user shouldn't have to open the chat to close it if they want to, this should be a clickable button that doesn't draw attention to itself and is red.

this is the component that needs this change → https://github.com/Dun-sin/Whisper/blob/main/client/src/pages/Start.jsx

### Screenshots

7jdXrkrFZG

### PR DESCRIPTION
**Pull request by kartik-raj7**
**My PR closes #677**

# 👨‍💻 Changes proposed(What did you do ?)

Updated the useEffect hook in the Start.jsx file to check if the app has a currentChatId key. If it does, the user is now automatically redirected to the chat page, removing the need to manually open the chat. Consequently, I've removed the conditional display of the "Open Chat" and "Start" options in the Link, as the app now handles the redirection based on the presence of currentChatId key in app object.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

### CODE REVIEW

**Comment by Dun-sin** [comment]
Your PR doesn't solve the issue, please read the issue description carefully and fix your PR as needed

**Comment by kartik-raj7** [comment]
> Your PR doesn't solve the issue, please read the issue description carefully and fix your PR as needed

Could you please elaborate the issue a bit, that would be really helpful

**Comment by Dun-sin** [comment]
> > Your PR doesn't solve the issue, please read the issue description carefully and fix your PR as needed
> 
> Could you please elaborate the issue a bit, that would be really helpful
> 
> Do I need to create a button which gives option to close the chat on homepage next to open chat?

That's what the issue says

**Comment by Dun-sin** [comment]
@kartik-raj7 are you still interested in this?

**Comment by kartik-raj7** [comment]
> @kartik-raj7 are you still interested in this?

Yes I am, will do the necessary changes

**Comment by Dun-sin** [comment]
@kartik-raj7 you have 4 more days

**Pull request closed without merging**
