### PR TITLE
Feat login id validation

### LINKED ISSUE #716: [FEATURE] FRONT-END: Validate loginId to be a valid uuid
### Description

Code: https://github.com/Dun-sin/Whisper/blob/1c1224036887cd9981d6c389e987569c07193976/client/src/context/AuthContext.jsx#L30

### Screenshots

_No response_

### Additional information

_No response_

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Gopal-001**
**My PR closes #716 **

# 👨‍💻 Changes proposed(What did you do ?)
during the merging process the condition got refactored causing breaking of login part.
redo the condition.
```
  if (!id && (typeof id !== 'string' || !userIDPattern.test(id))) {
```
here if email login than id will be undefined so condition so we are checking if id is coming than moving fwd to verify the type and regex pattern, and if it's invalid we'll just move ahead.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

NA

### CODE REVIEW

**Comment by Dun-sin** [comment]
@Gopal-001 think it fails because your solution wasn't reviewed properly by me, but not because of that code specifically.

but because you were trying to validate the ID, your code is wrong and my refactor was what was needed, you didn't test this in local, please do next time

but yeah will fix it on my end and push it, will share the commit if you would like to see the solution

**Comment by Dun-sin** [comment]
@Gopal-001 actually you were right

**Comment by Dun-sin** [comment]
@Gopal-001 had to revert to the old code in server, but kept the one in frontend. Thanks

**Comment by Gopal-001** [comment]
> @Gopal-001 think it fails because your solution wasn't reviewed properly by me, but not because of that code specifically.
> 
> but because you were trying to validate the ID, your code is wrong and my refactor was what was needed, you didn't test this in local, please do next time
> 
> but yeah will fix it on my end and push it, will share the commit if you would like to see the solution

@Dun-sin sure thanks for the feedback, although I've already teseted it but if you're looking into it.However pls refer to this commit https://github.com/Dun-sin/Whisper/pull/729/commits/308b6065a2edc443fe79e28b8c55d7163d822298 if in page `server/utils/helper.js` we just replace this condition back `if(!id && (typeof id !== 'string' || !userIDPattern.test(id)))` it will work properly.

**Comment by Dun-sin** [comment]
> 
> > @Gopal-001 think it fails because your solution wasn't reviewed properly by me, but not because of that code specifically.
> > 
> > but because you were trying to validate the ID, your code is wrong and my refactor was what was needed, you didn't test this in local, please do next time
> > 
> > but yeah will fix it on my end and push it, will share the commit if you would like to see the solution
> 
> @Dun-sin sure thanks for the feedback, although I've already teseted it but if you're looking into it.However pls refer to this commit https://github.com/Dun-sin/Whisper/pull/729/commits/308b6065a2edc443fe79e28b8c55d7163d822298 if in page `server/utils/helper.js` we just replace this condition back `if(!id && (typeof id !== 'string' || !userIDPattern.test(id)))` it will work properly.
> 

It works but it's not an ideal solution

**Pull request closed without merging**
