### PR TITLE
fix: Error in parsing messages containing bad words

### LINKED ISSUE #320: [BUG] Error in parsing messages containing bad words
### Description

When I send a message that contains a bad word, the app crashes for me and my buddy, I expect a warning message, not a crashed app.

The bug is coming from this line:
https://github.com/Dun-sin/Whisper/blob/23fe79f946e8b1e5a67c8592bd778ef23100fa35/client/src/components/Chat.jsx#L441

This is in the same group as #319, perhaps creating a new milestone would be great.

### Screenshots

_No response_

### Additional information

_No response_

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by VaibhavKVerma**
# Fixes: Error in parsing messages containing bad words

**My PR closes #320**

# 👨‍💻 Changes proposed
- The **warningMessage** function returns JSX element which markdownIt could not parse. So just added a check condition.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

# 📷 Screenshots

Screenshot 2023-09-28 204040
Screenshot 2023-09-28 204056

### CODE REVIEW

**Comment by Dun-sin** [comment]
@VaibhavKVerma  can you explain how your solution fixes it and did you test that it still displays/works like it should?

**Comment by VaibhavKVerma** [comment]
@Dun-sin So here the markdownIt only parses string and from the function if it is a bad word then a JSX element is being returned which throws error.
So there are two ways two solve :- 
1. Either I could have returned it in string format rather than JSX from the **warningMessage** function.
2. Or add a check whether the **message** is string or not.

Yes I tested it with the list of badWords file.I have attached screenshot also for same.

**Comment by Dun-sin** [comment]
> @Dun-sin So here the markdownIt only parses string and from the function if it is a bad word then a JSX element is being returned which throws error. So there are two ways two solve :-
> 
>     1. Either I could have returned it in string format rather than JSX from the **warningMessage** function.
> 
>     2. Or add a check whether the **message** is string or not.
> 
> 
> Yes I tested it with the list of badWords file.I have attached screenshot also for same.

that makes sense, thank you for explaining

**Review by Dun-sin — APPROVED** [review]
Your PR is accepted thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

**Pull request merged**
