### PR TITLE
styles : changed the span to a button for the is bad words element #666

### LINKED ISSUE #666: [OTHER] change the span to a button for the is bad words element
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L502-L513

### Additional information

This issue depends on #663 

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

### PR DESCRIPTION
**Pull request by vikashjoshi187**
# [OTHER] change the span to a button for the is bad words element

My PR closes #666

# 👨‍💻 Changed the span tags to button tags

✅ Done 

Screenshot 2024-09-15 at 5 14 07 PM

### CODE REVIEW

**Comment by vikashjoshi187** [comment]
Hi everyone,

This is my first contribution to this project, and I am excited to be part of it. I’ve done my best to follow the guidelines, but if there are any mistakes or improvements needed, I sincerely apologize and welcome any feedback to help me learn and improve.

Thank you for reviewing my work!

Best regards,
Vikas Joshi

**Comment by Dun-sin** [comment]
@vikashjoshi187 thanks for wanting to contribute, but you broke one of the most important guidelines in open source, try reading our [contributing guideline](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) instead of just the readme

**Comment by Dun-sin** [comment]
Will close this, hope you continue to contribute to this project the proper way.

**Comment by vikashjoshi187** [comment]
Thanks @Dun-sin i will keep that i mind in my next contribution.

**Pull request closed without merging**
