### PR TITLE
fix: removed underline and bg change on hover Start

### LINKED ISSUE #111: [FEATURE] Remove change of colour hover effect
### Description

When you hover the start button the colour changes, and it has a text underline(the default style for a link), remove that

Element that the change should apply to
https://github.com/Dun-sin/Whisper/blob/774dcd3c91d6b65c3e3e3ebce6c09e16e646956a/client/src/pages/Start.jsx#L21-L29

### Screenshots

image

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

### PR DESCRIPTION
**Pull request by kaustav202**
## 🛠️ Fixes Issue

 fixes #111 

## 👨‍💻 Changes proposed

Add styling to mitigate the default behavior of <Link> component 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

NA - Because cursor hides while taking screenshot

### CODE REVIEW

**Comment by Dun-sin** [comment]
Kindly delete this PR, you are making changes on the main branch which isn't ethical
Follow this on how to contribute properly [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#-how-to-make-a-pull-request)

**Comment by kaustav202** [comment]
> Kindly delete this PR, you are making changes on the main branch which isn't ethical Follow this on how to contribute properly [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#-how-to-make-a-pull-request)

I have read the guidelines.. merge this PR, I will remove my fork and re-fork it on my account so there won't be any conflicts

**Comment by kaustav202** [comment]
> > > Kindly delete this PR, you are making changes on the main branch which isn't ethical Follow this on how to contribute properly [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#-how-to-make-a-pull-request)
> > 
> > 
> > I have read the guidelines.. merge this PR, I will remove my fork and re-fork it on my account so there won't be any conflicts
> 
> Look my friend, either do as I say or close this PR and I will assign this to someone else, thank you

Okay sure, but I'm new to open source.. would you mind elaborating how this could be a problem so that I don't repeat this

**Comment by Dun-sin** [comment]
> > > > Kindly delete this PR, you are making changes on the main branch which isn't ethical Follow this on how to contribute properly [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#-how-to-make-a-pull-request)
> > > 
> > > 
> > > I have read the guidelines.. merge this PR, I will remove my fork and re-fork it on my account so there won't be any conflicts
> > 
> > Look my friend, either do as I say or close this PR and I will assign this to someone else, thank you
> 
> Okay sure, but I'm new to open source.. would you mind elaborating how this could be a problem so that I don't repeat this

It causes a problem because if you push to the main branch and it ends up with a bug then it will be hard to fix. But if you create your own branch and it won't be a problem. Can just delete yours.


Always create a new branch. Anyway closing this, create a pr the proper way

**Pull request closed without merging**
